---
- hosts: all
  become: yes

  tasks:
    - name: install httpd
      yum:
        name: httpd
        state: latest

    - name: create index.html file
      file:
        path: /www/var/index.html
        state: touch

    - name: enter html text into the file
      lineinfile:
        path: /www/var/index.html
        line: "ansible playbook works !!"

    - name: start httpd service
      service:
        name: httpd
        state: started
